server:
  port: 9120

spring:
  banner:
    location: banner.txt

  application:
    name: gumeng

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.10.187:3306/gumeng
    username: gumeng_user
    password: gumeng_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000       # 10分钟（单位：毫秒）
      max-lifetime: 1800000       # 30分钟（单位：毫秒，建议小于 MySQL 的 wait_timeout）
      connection-timeout: 30000   # 30秒（获取连接超时时间）
      validation-timeout: 5000    # 5秒（连接验证超时时间）
      leak-detection-threshold: 60000  # 60秒（检测连接泄漏）
      keepalive-time: 30000      # 30秒（定期发送保活探测）
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/gumeng
#    username: root
#    password: 123456

  #邮箱配置
  mail:
    host: smtp.qq.com  #发送邮件的服务器地址
    port: 465  # 使用465端口
    username: 2391454607@qq.com  # 邮箱账号
    password: kaaeauniqbfbdhhd  #开启 IMAP/SMTP 服务 授权码
    default-encoding: UTF-8
    protocol: smtps  # 使用smtps协议
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

  data:
    redis:
      host: 127.0.0.1      # Redis 服务器地址
      port: 6379            # Redis 服务器端口
      database: 0           # 使用的数据库索引（默认是 0）
      timeout: 5000         # 连接超时时间（单位：毫秒）
      lettuce:
        pool:
          max-active: 8     # 连接池最大连接数
          max-idle: 10       # 连接池最大空闲连接数
          min-idle: 0       # 连接池最小空闲连接数
          max-wait: -1ms    # 连接池最大阻塞等待时间（-1 表示无限制）

  security:
    user:
      name: admin
      password: admin


mybatis-plus:
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启实体类中驼峰命名和数据库中下划线命名的自动转换
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

aj:
  captcha:
    cache-type: local
    # cache-number: 1000  # local缓存的阈值,达到这个值，清除缓存
    # timing-clear: 180   # local定时清除过期缓存(单位秒),设置为0代表不执行

    type: default         # 验证码类型default两种都实例化。
    water-mark: "\u6211\u7684\u6C34\u5370"  # 右下角水印文字(我的水印)
    # water-font: WenQuanZhengHei.ttf  # 右下角水印字体
    # font-type: WenQuanZhengHei.ttf   # 点选文字验证码的文字字体
    slip-offset: 5        # 校验滑动拼图允许误差偏移量(默认5像素)
    aes-status: true      # aes加密坐标开启或者禁用(true|false)
    interference-options: 2  # 滑动干扰项(0/1/2)

    font-style: 1         # 点选字体样式 默认Font.BOLD
    font-size: 25         # 点选字体字体大小
    # click-word-count: 4  # 点选文字个数,存在问题，暂不支持修改

    history-data-clear-enable: false

    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: false
    req-get-lock-limit: 5      # 验证失败5次，get接口锁定
    req-get-lock-seconds: 360  # 验证失败后，锁定时间间隔,s
    req-get-minute-limit: 30   # get接口一分钟内请求数限制
    req-check-minute-limit: 60 # check接口一分钟内请求数限制
    req-verify-minute-limit: 60 # verify接口一分钟内请求数限制


# 七牛云配置
qiniu:
  accessKey: lZSkzZ4ovrprg-GBfsU6XpI4ga-F2Yqzj3bbQxEN
  secretKey: _xKceL1z0klae_1QxdUfCbXFOeJiPHe4Hki_Ppdn
  bucket: gmls
  domain: sw8nkdw7h.hn-bkt.clouddn.com
  region: huanan  # 区域名

# 添加敏感词配置
custom:
  sensitive-word:
    path: sensitive_word/sensitive-words.txt

  # 纯真IP库配置
  ip:
    qqwry:
      enabled: true  # 是否启用纯真IP库
      path: chunZhenIp/qqwry.dat  # 纯真IP库路径
      autoLoad: true  # 是否自动加载
      charset: gbk  # 编码格式
