server:
  port: 8080


spring:
  application:
    name: gumeng

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://175.178.10.187:3306/gumeng
#    username: gumeng_user
#    password: sail123
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gumeng
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1       # Redis 服务器地址
      port: 6379            # Redis 服务器端口
      password:    # Redis 密码（如果没有密码，可以省略）
      database: 0           # 使用的数据库索引（默认是 0）
      timeout: 2000         # 连接超时时间（单位：毫秒）
      lettuce:
        pool:
          max-active: 8     # 连接池最大连接数
          max-idle: 10       # 连接池最大空闲连接数
          min-idle: 0       # 连接池最小空闲连接数
          max-wait: -1ms    # 连接池最大阻塞等待时间（-1 表示无限制）


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启实体类中驼峰命名和数据库中下划线命名的自动转换


pagehelper:
  #数据库类型
  helperDialect: mysql
  #开启分页合理化
  reasonable: true
  #开启支持方法参数
  supportMethodsArguments: true
  #统计总记录数的 SQL 查询语句
  #如何判断当前有多少页
  #总页数/每页页数=当前有多少页
  #{list:[],total:100}
  params: count = countSql

